"""Add survey_id to Question

Revision ID: 02366259558e
Revises: 
Create Date: 2024-01-30 13:27:25.736756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02366259558e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('survey_id', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('text', sa.String(length=500), nullable=False))
    op.add_column('question', sa.Column('question_type', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'question_type')
    op.drop_column('question', 'text')
    op.drop_column('question', 'survey_id')
    # ### end Alembic commands ###
